# Generated by Django 6.0.5 on 2026-06-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='profit_share_percentage',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=5),
        ),
    ]
