# Generated by Django 6.0.5 on 2026-06-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_partner_profit_share_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitBuyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('number_of_units', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_due', models.DecimalField(decimal_places=2, help_text='Total money they need to give', max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, help_text='Money already paid', max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
