# Generated by Django 6.0.5 on 2026-06-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_unitbuyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitbuyer',
            name='name',
            field=models.CharField(choices=[('Raju', 'Raju'), ('Ramesh', 'Ramesh'), ('Govindha Raju', 'Govindha Raju')], max_length=150),
        ),
    ]
