# Generated by Django 6.0.5 on 2026-06-23 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_unitbuyer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitbuyer',
            name='amount_due',
        ),
        migrations.RemoveField(
            model_name='unitbuyer',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='unitbuyer',
            name='date',
        ),
        migrations.RemoveField(
            model_name='unitbuyer',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='unitbuyer',
            name='number_of_units',
        ),
        migrations.AlterField(
            model_name='unitbuyer',
            name='name',
            field=models.CharField(choices=[('Raju', 'Raju'), ('Ramesh', 'Ramesh'), ('Govindha Raju', 'Govindha Raju')], max_length=150, unique=True),
        ),
        migrations.CreateModel(
            name='UnitBuyerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('units_added', models.DecimalField(decimal_places=2, default=0.0, help_text='Units added in this transaction', max_digits=10)),
                ('amount_due', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount owed for this transaction', max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount paid in this transaction', max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.unitbuyer')),
            ],
        ),
    ]
